### ISSUE TITLE
JSON encoding issues when using batching

### ISSUE THREAD

**Issue by kcoderhere** [facebook-csharp-sdk/facebook-csharp-sdk#315]
I documented the issue here: http://stackoverflow.com/questions/26598595/why-is-facebook-post-batching-failing-with-graphbatchexception-0

Here is the code I'm using to test batching using the C# Facebook SDK 6.8.0 from NuGet:

```c#
var client = new FacebookClient();
client.AppId = application.FacebookAppId;
client.AppSecret = application.FacebookAppSecret;

var batchedRequests = new List<FacebookBatchParameter>();
batchedRequests.Add(new FacebookBatchParameter()
{
    HttpMethod = HttpMethod.Post,
    Path = "2982XXXXXXXXXX001/feed",
    Parameters = new Dictionary<string, object>
    {
        {"access_token", "CAAK9UGtbUaMBAKX..."},
        {"message", "Check out our stuff at Google: " + DateTime.UtcNow.Ticks},
        {"link", "http://www.google.com"}
    }
});
batchedRequests.Add(new FacebookBatchParameter()
{
    HttpMethod = HttpMethod.Post,
    Path = "755XXXXXXXXXX21/photos",
    Parameters = new Dictionary<string, object>
    {
        {"access_token", "CAAK9UGtbUaMBAA6..."},
        {"message", "Lions, oh my! " + DateTime.UtcNow.Ticks},
        {"url", "http://i.imgur.com/DVSsmpa.jpg"}
    }
});
batchedRequests.Add(new FacebookBatchParameter()
{
    HttpMethod = HttpMethod.Post,
    Path = "2982XXXXXXXXXX001/feed", // Same as first
    Parameters = new Dictionary<string, object>
    {
        {"access_token", "CAAK9UGtbUaMBAKX..."}, // Same as first
        {"message", "Check out our stuff at Facebook: " + DateTime.UtcNow.Ticks},
        {"link", "http://www.facebook.com"}
    }
});

var batchedParams = new Dictionary<string, object>();
batchedParams.Add("access_token", defaultPage.PageAccessToken);

dynamic facebookResponse = client.Batch(batchedRequests.ToArray(), batchedParams);
```

If I comment out any one of the three batchedRequests.Add() calls, it works fine.

It only breaks if all three are together.

Here's the error I get:

```
Unhandled Exception: Facebook.FacebookApiException: (GraphBatchException - #0) Batch parameter must be a JSON array
   at Facebook.FacebookClient.ProcessResponse(HttpHelper httpHelper, String responseString, Type resultType, Boolean containsEtag, IList`1 batchEtags)
   at Facebook.FacebookClient.Api(HttpMethod httpMethod, String path, Object parameters, Type resultType)
   at Facebook.FacebookClient.Post(String path, Object parameters)
   at Facebook.FacebookClient.Post(Object parameters)
   at Facebook.FacebookClient.Batch(FacebookBatchParameter[] batchParameters, Object parameters)
   at FacebookTest.Program.FacebookBatchTest() in c:\Test\Program.cs:line 81
   at FacebookTest.Program.Main(String[] args) in c:\Test\Program.cs:line 23
```

**Comment by kcoderhere** [comment]
Any response to this? Is this still even in development?  I noticed there's no release version for the new API that came out and FB is going to shutting this down in a few months...

**Comment by crazybernie** [comment]
I have exactly the same problem. My code for batch posting to Facebook does not work in SDK version 6.8.0 but SDK version 6.4.2 and exactly the same code is working. I've tried different amount of batch parameters but only  1 parameter work in 6.8.0 where as in SDK 6.4.2 I can  use a maximum of 40 parameters before facebook starts returning errors.

**Comment by PSanetra** [comment]
I created a pull request, which should fix this problem: https://github.com/facebook-csharp-sdk/facebook-csharp-sdk/pull/327

**Comment by prabirshrestha** [comment]
Thanks to @PSanetra for the PR. A new version has been pushed to nuget.
https://www.nuget.org/packages/Facebook/7.0.5-beta

**Comment by oneEyedOdin** [comment]
@kcoderhere Did the PR fix the issue for you?  I'm still seeing this issue in the 7.0.9-beta release.
